name: "build-scaffold-zome-module"
on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push: 
    branches: [ main, 'main-**' ]
  pull_request: 
    branches: [ main, 'main-**' ]

jobs:
  build-scaffold-zome-module:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, macos-13]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - uses: cachix/install-nix-action@v27
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
          nix_path: nixpkgs=channel:nixos-24.11

      - uses: cachix/cachix-action@v15
        with:
          name: holochain-ci

      - uses: cachix/cachix-action@v15
        with:
          name: darksoil-studio

      - name: Build scaffold-zome-module
        env:
          CACHIX_AUTH_TOKEN: "${{ secrets.DARKSOIL_CACHIX_AUTH_TOKEN }}"
        run: |
          cachix watch-exec darksoil-studio -- nix build --no-update-lock-file --accept-flake-config -L .#scaffold-zome-module
          cachix push darksoil-studio $(nix path-info --json --accept-flake-config --no-warn-dirty .#scaffold-zome-module | nix run nixpkgs#jq -- -r 'keys[0]')

      - name: Build scaffold-zome-module
        if: github.event_name != 'pull_request' && github.ref_name == 'main'
        env:
          CACHIX_AUTH_TOKEN: "${{ secrets.DARKSOIL_CACHIX_AUTH_TOKEN }}"
        run: |
          cachix pin darksoil-studio scaffold-zome-module $(nix path-info --json --accept-flake-config --no-warn-dirty .#scaffold-zome-module | nix run nixpkgs#jq -- -r 'keys[0]')
